# Generated by Django 3.2.5 on 2021-07-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.PositiveIntegerField()),
                ('train_car_number', models.PositiveIntegerField()),
                ('trip_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('source', models.CharField(choices=[('cairo', 'cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Dakahlia', 'Dakahlia'), ('Sharkia', 'Sharkia'), ('Menoufia', 'Menoufia'), ('Qalyubia', 'Qalyubia'), ('Beheira', 'Beheira'), ('Gharbia', 'Gharbia'), ('Port Said', 'Port Said'), ('Damietta', 'Damietta'), ('Ismailia', 'Ismailia'), ('Suez', 'Suez'), (' Kafr El Sheikh', ' Kafr El Sheikh'), ('Fayoum', 'Fayoum'), ('Beni Suef', 'Beni Suef'), ('Matrouh', 'Matrouh'), ('El Alamein ', 'El Alamein '), ('North Sinai', 'North Sinai'), ('Minya', 'Minya'), ('Sinai', 'Sinai'), ('Minya', 'Minya'), ('Assiut', 'Assiut'), ('Sohag', 'Sohag'), ('Qena', 'Qena'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan'), ('Red Sea', 'Red Sea')], max_length=50)),
                ('destination', models.CharField(choices=[('cairo', 'cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Dakahlia', 'Dakahlia'), ('Sharkia', 'Sharkia'), ('Menoufia', 'Menoufia'), ('Qalyubia', 'Qalyubia'), ('Beheira', 'Beheira'), ('Gharbia', 'Gharbia'), ('Port Said', 'Port Said'), ('Damietta', 'Damietta'), ('Ismailia', 'Ismailia'), ('Suez', 'Suez'), (' Kafr El Sheikh', ' Kafr El Sheikh'), ('Fayoum', 'Fayoum'), ('Beni Suef', 'Beni Suef'), ('Matrouh', 'Matrouh'), ('El Alamein ', 'El Alamein '), ('North Sinai', 'North Sinai'), ('Minya', 'Minya'), ('Sinai', 'Sinai'), ('Minya', 'Minya'), ('Assiut', 'Assiut'), ('Sohag', 'Sohag'), ('Qena', 'Qena'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan'), ('Red Sea', 'Red Sea')], max_length=50)),
                ('NumberOfSeats', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SingleSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.PositiveIntegerField()),
                ('train_car_number', models.PositiveIntegerField()),
                ('trip_number', models.PositiveIntegerField()),
                ('NumberSeat', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('SS_date', models.DateField()),
                ('SS_time', models.TimeField()),
                ('SS_source', models.CharField(choices=[('cairo', 'cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Dakahlia', 'Dakahlia'), ('Sharkia', 'Sharkia'), ('Menoufia', 'Menoufia'), ('Qalyubia', 'Qalyubia'), ('Beheira', 'Beheira'), ('Gharbia', 'Gharbia'), ('Port Said', 'Port Said'), ('Damietta', 'Damietta'), ('Ismailia', 'Ismailia'), ('Suez', 'Suez'), (' Kafr El Sheikh', ' Kafr El Sheikh'), ('Fayoum', 'Fayoum'), ('Beni Suef', 'Beni Suef'), ('Matrouh', 'Matrouh'), ('El Alamein ', 'El Alamein '), ('North Sinai', 'North Sinai'), ('Minya', 'Minya'), ('Sinai', 'Sinai'), ('Minya', 'Minya'), ('Assiut', 'Assiut'), ('Sohag', 'Sohag'), ('Qena', 'Qena'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan'), ('Red Sea', 'Red Sea')], max_length=50)),
                ('SS_destination', models.CharField(choices=[('cairo', 'cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Dakahlia', 'Dakahlia'), ('Sharkia', 'Sharkia'), ('Menoufia', 'Menoufia'), ('Qalyubia', 'Qalyubia'), ('Beheira', 'Beheira'), ('Gharbia', 'Gharbia'), ('Port Said', 'Port Said'), ('Damietta', 'Damietta'), ('Ismailia', 'Ismailia'), ('Suez', 'Suez'), (' Kafr El Sheikh', ' Kafr El Sheikh'), ('Fayoum', 'Fayoum'), ('Beni Suef', 'Beni Suef'), ('Matrouh', 'Matrouh'), ('El Alamein ', 'El Alamein '), ('North Sinai', 'North Sinai'), ('Minya', 'Minya'), ('Sinai', 'Sinai'), ('Minya', 'Minya'), ('Assiut', 'Assiut'), ('Sohag', 'Sohag'), ('Qena', 'Qena'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan'), ('Red Sea', 'Red Sea')], max_length=50)),
                ('Booking', models.BooleanField(default=False)),
            ],
        ),
    ]
