# Generated by Django 3.2.5 on 2021-07-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Balance',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='WalletId',
            field=models.PositiveIntegerField(max_length=20),
        ),
    ]
