# Generated by Django 3.2.5 on 2021-07-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_auto_20210719_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Balance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='WalletId',
            field=models.PositiveIntegerField(),
        ),
    ]
