# Generated by Django 3.2.5 on 2021-07-05 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AddingTrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
