# Generated by Django 3.2.5 on 2021-07-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddingTrain', '0003_auto_20210706_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='distnation',
            new_name='destination',
        ),
    ]
